OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "hsbc_pdf-1.pdf"
  file_format: "markdown"